### ISSUE TITLE
I get this error when running with angular2 universal

### ISSUE THREAD

**Issue by amishgandhi** [leewinder/ng2-file-drop#20]
/Users/tapolo/dropsecure-git/master/ds-angular2/node_modules/ng2-file-drop/directives/file-drop.directive.js:126
    __metadata("design:paramtypes", [Event]),
                                     ^

ReferenceError: Event is not defined
    at Object.<anonymous> (/Users/tapolo/dropsecure-git/master/ds-angular2/node_modules/ng2-file-drop/directives/file-drop.directive.js:126:38)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tapolo/dropsecure-git/master/ds-angular2/node_modules/ng2-file-drop/module/file-drop.module.js:11:29)
    at Module._compile (module.js:541:32)

**Comment by leewinder** [comment]
Updated to Angular ^4.1.3 as a minimum in v1.0.0 - Pull request [#28](https://github.com/leewinder/ng2-file-drop/pull/28)
