### ISSUE TITLE
build failed when using Angular Cli v1.7.3 and Angular v5.2.7

### ISSUE THREAD

**Issue by dizhar** [leewinder/ng2-file-drop#51]
ERROR in ./node_modules/ng2-file-drop/node_modules/tslerp/index.ts
Module build failed: Error: C:\loltlv\node_modules\ng2-file-drop\node_modules\tslerp\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\loltlv\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\loltlv\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by lrabuffetti** [comment]
I have the same error

**Comment by ceeliro** [comment]
Same,

**Comment by krbnr** [comment]
same

**Comment by vasconcelosvcd** [comment]
Same.

EDIT:  Fixed with #50 

include below tsconfig.js.

```
"include": [
"src//*",
"node_modules/tslerp/index.ts",
"node_modules/ng2-file-drop/index.ts",
"node_modules/ng2-file-drop//.ts",
"node_modules/tslerp/**/.ts"
]
```

**Comment by KumailHussain** [comment]
error went but file frop is not working

**Comment by dizhar** [comment]
I fixed it by adding the following to tsconfig,json

  "include": [
    "src//*",
    "node_modules/ng2-file-drop/node_modules/tslerp/index.ts",
    "node_modules/ng2-file-drop/index.ts",
    "node_modules/tslerp/**/.ts"
  ]


I hope this helps someone :)
